stages:
  - build
  - docker
  - deploy

# BUILD STAGE
build-main:
  stage: build
  image: maven:3.8.4-jdk-17
  script:
    - mvn clean install -Dmaven.test.skip=true
  artifacts:
    paths:
      - target/
  only:
    - master

# DOCKER STAGE
docker-main:
  stage: docker
  image: docker:latest
  before_script:
    - docker login -u $DOCKER_LOGIN -p $DOCKER_TOKEN $CI_REGISTRY
  script:
    - docker build --tag $CI_REGISTRY_IMAGE:back .
    - docker push $CI_REGISTRY_IMAGE:back
  dependencies:
    - build-main
  only:
    - master

# DEPLOY STAGE
deploy-main:
  stage: deploy
  before_script:
    - "which ssh-agent || (apk update && apk add openssh-client bash curl)"
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - bash -c "ssh-add <(echo \"$SSH_PRIVATE_KEY\")"
    - export COMPOSE_HTTP_TIMEOUT=200
    - ssh root@$HOST "docker compose -f ~/docker-compose.yml down --remove-orphans"
    - ssh root@$HOST "docker compose -f ~/docker-compose.yml pull"
    - ssh root@$HOST "docker compose -f ~/docker-compose.yml up -d"
  dependencies:
    - build-main
  only:
    - master
